# - id: home_lights_on
#   alias: Home > Lights On
#   trigger:
#     platform: state
#     entity_id: person.tomi
#     from: not_home
#     to: home
#   condition: []
#   action:
#     service: light.turn_on
#     entity_id: light.living_room

# - id: home_lights_off
#   alias: Home > Lights Off
#   trigger:
#     platform: state
#     entity_id: person.tomi
#     from: home
#     to: not_home
#   condition: []
#   action:
#     service: light.turn_off
#     entity_id: light.living_room
