  - platform: mikrotik
    host: !secret mikrotik_host
    username: !secret mikrotik_username
    password: !secret mikrotik_password
    consider_home: 360
    new_device_defaults:
      track_new_devices: false