  - platform: tomato
    host: !secret tomato_host
    username: !secret tomato_username
    password: !secret tomato_password
    http_id: !secret tomato_http_id
    new_device_defaults:
      track_new_devices: false