version: '2'

volumes:
  volume_homeassistant:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/tomi/Documents/git/friday/homeassistant/config

services:

  pihole:
    entrypoint: ["echo", "PiHole service disabled for development environment."]

  homeassistant:
    build: 
      dockerfile: Dockerfile.development

  myhabeetat:
    build: 
      dockerfile: Dockerfile.development