version: "2"

volumes:
  volume_pihole:
  volume_dnsmasq:

services:
  pihole:
    build: ./pihole
    privileged: true
    ports:
      - 80:80
    volumes:
       - volume_pihole:/etc/pihole/
       - volume_dnsmasq:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped