version: '2'

volumes:
  volume_pihole:
  volume_dnsmasq:
  volume_homeassistant:

services:

  # pihole:
  #   build: ./pihole
  #   privileged: true
  #   volumes:
  #      - volume_pihole:/etc/pihole/
  #      - volume_dnsmasq:/etc/dnsmasq.d/
  #   dns:
  #     - 127.0.0.1
  #     - 1.1.1.1
  #   cap_add:
  #     - NET_ADMIN
  #   network_mode: host

  homeassistant:
    build: 
      context: ./homeassistant
      dockerfile: Dockerfile.rpi
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - volume_homeassistant:/config
    privileged: true
    restart: always
    ports: 
      - 8123:8123
