version: '2'

volumes:
  volume_pihole:
  volume_dnsmasq:
  volume_homeassistant:

services:

  pihole:
    build: ./pihole
    privileged: true
    volumes:
       - volume_pihole:/etc/pihole/
       - volume_dnsmasq:/etc/dnsmasq.d/
    environment:
      WEB_PORT: 8089
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped

  homeassistant:
    build: 
      context: ./homeassistant
      dockerfile: Dockerfile.production
    volumes:
      - volume_homeassistant:/config
    privileged: true
    restart: always
    ports: 
      - 8123:8123
    depends_on:
      - myhabeetat
      - pihole

  myhabeetat:
    build: 
      context: ./myhabeetat
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - 8080:8080