version: "2"

volumes:
  volume_pihole:
  volume_dnsmasq:

services:
  pihole:
    image: pihole/pihole:latest
    privileged: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
       - volume_pihole:/etc/pihole/
       - volume_dnsmasq:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: unless-stopped